server.port=8083

spring.datasource.url=jdbc:mysql://localhost:8081/cocoeventsrelacional
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=vfercms1221

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.application.name=apirelacional

management.tracing.sampling.probability=1.0

logging.pattern.level='%5p [${spring.application.name}, %X{traceId}:-}, %X{spanId:-}]'

logging.level.org.springframework.web=DEBUG

debug=true